ENV["COCOAPODS_DISABLE_STATS"] = "true"

source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
workspace 'SwiftyExtensionsHelper'

target 'SwiftyExtensionsHelper' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pretty

  # logger
  pod 'CocoaLumberjack', '~> 3.2'  # 避免一些警告
  pod 'CocoaLumberjack/Swift', '~> 3.2'
  pod 'NSLogger/Swift', '~> 1.8'
  # CocoaLumberjack -> NSLogger
  # pod 'XCDLumberjackNSLogger', '~> 1.1'

end
